server:
  port: 8020
spring:
  application:
    name: Search
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka
